services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python electro/manage.py makemigrations && python electro/manage.py migrate && python electro/manage.py runserver 0.0.0.0:80"
    volumes:
      - .:/app:rw
    ports:
      - "6002:6003"
    environment:
      - DJANGO_SETTINGS_MODULE=main.settings
    depends_on:
      - db
      - rediska
      - celery
      - celery-beat

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: "celery -A electro.celery:app worker -l info --concurrency=2"
    volumes:
      - .:/app:rw
    depends_on:
      - db
      - rediska

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: "celery -A electro.celery:app beat -l info"
    volumes:
      - .:/app:rw
    depends_on:
      - db
      - rediska

  db:
    image: postgres:14-bookworm
    container_name: database
    hostname: postgres
    environment:
      - POSTGRES_DB=rocket
      - POSTGRES_USER=rocket
      - POSTGRES_PASSWORD=rocketdata
    restart: always
    ports:
      - "5432:5432"
  
  rediska:
    image: redis:8.0-M04-bookworm
    container_name: redis
    restart: always
    environment:
    - REDIS_PASSWORD=redis
    ports:
      - "6381:6379"