# Generated by Django 5.1.7 on 2025-04-04 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='Название', max_length=50)),
                ('email', models.EmailField(db_comment='E-mail', max_length=254, unique=True)),
                ('country', models.CharField(db_comment='Страна', max_length=64)),
                ('city', models.CharField(db_comment='Город', max_length=64)),
                ('street', models.CharField(db_comment='Улица', max_length=128)),
                ('house_number', models.CharField(db_comment='Номер дома')),
                ('debt_to_producer', models.DecimalField(db_comment='Задолженность перед поставщиком', decimal_places=2, default=0, max_digits=10)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('level', models.IntegerField(choices=[(0, 'Завод'), (1, 'Дистрибьютор'), (2, 'Дилерский центр'), (3, 'Крупная розничная сеть'), (4, 'Индивидуальный предприниматель')], default=0)),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producers', to='retail.networknode')),
            ],
            options={
                'verbose_name': 'Информация о поставщиках',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('network_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='retail.networknode')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='Название продукта', max_length=256)),
                ('model', models.CharField(db_comment='Модель продукта', max_length=128)),
                ('release_date', models.DateTimeField(db_comment='Дата выхода')),
                ('network_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='retail.networknode')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
